# Generated by Django 3.2.3 on 2021-05-25 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iotupdate', '0002_device_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.CharField(max_length=255, verbose_name='Temp')),
                ('timestamp', models.CharField(max_length=255, verbose_name='Timestamp')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotupdate.device')),
            ],
            options={
                'verbose_name': 'Device Temp',
                'verbose_name_plural': 'Device Temps',
            },
        ),
    ]
