# Generated by Django 3.2.3 on 2021-06-05 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iotupdate', '0003_devicetemp'),
    ]

    operations = [
        migrations.CreateModel(
            name='RollbackLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Detail')),
                ('time_execution', models.TimeField(blank=True, null=True, verbose_name='Time Execution')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollback_logs', to='iotupdate.device')),
            ],
            options={
                'verbose_name': 'Rollback Log',
                'verbose_name_plural': 'Rollback Logs',
            },
        ),
    ]
