# Generated by Django 3.2.3 on 2021-06-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotupdate', '0004_rollbacklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollbacklog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
    ]
