# Generated by Django 3.2.3 on 2021-06-05 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iotupdate', '0005_rollbacklog_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rollbacklog',
            name='time_execution',
        ),
    ]
