# Generated by Django 3.2.3 on 2021-06-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotupdate', '0006_remove_rollbacklog_time_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollbacklog',
            name='time_execution',
            field=models.FloatField(blank=True, null=True, verbose_name='Time Execution'),
        ),
    ]
