# Generated by Django 3.2.3 on 2021-06-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotupdate', '0007_rollbacklog_time_execution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rollbacklog',
            name='device',
        ),
        migrations.AddField(
            model_name='rollbacklog',
            name='type',
            field=models.CharField(default='git revert', max_length=255, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
