# Generated by Django 3.2.3 on 2021-06-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotupdate', '0008_auto_20210605_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=255, verbose_name='Device')),
                ('version', models.CharField(max_length=255, verbose_name='Version')),
                ('file', models.FileField(upload_to='file-versions')),
                ('file_hash', models.CharField(max_length=255, verbose_name='File Hash')),
            ],
            options={
                'verbose_name': 'Package Version',
                'verbose_name_plural': 'Package Versions',
            },
        ),
    ]
