# Generated by Django 3.2.3 on 2021-06-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotupdate', '0010_auto_20210608_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageversion',
            name='tx_hash',
            field=models.CharField(default='6a4c39085fde4f5d95be69c872781a29', max_length=255, verbose_name='Tx Hash'),
        ),
    ]
