# Generated by Django 3.2.3 on 2021-06-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotupdate', '0011_packageversion_tx_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageversion',
            name='file',
            field=models.FileField(upload_to='media/file-versions'),
        ),
        migrations.AlterField(
            model_name='packageversion',
            name='tx_hash',
            field=models.CharField(default='dfb3fcf984c94958b2f17b9cc2968eb1', max_length=255, verbose_name='Tx Hash'),
        ),
    ]
