# Generated by Django 3.2.3 on 2021-06-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotupdate', '0012_auto_20210612_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageversion',
            name='file',
            field=models.FileField(upload_to='file-versions'),
        ),
        migrations.AlterField(
            model_name='packageversion',
            name='tx_hash',
            field=models.CharField(default='5f66e9f10d324868a56c4e78f4f9ff71', max_length=255, verbose_name='Tx Hash'),
        ),
    ]
