# Generated by Django 3.2.3 on 2021-06-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotupdate', '0013_auto_20210612_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageversion',
            name='tx_hash',
            field=models.CharField(default='8da33963c8a3411dad5f085a3bae4d36', max_length=255, verbose_name='Tx Hash'),
        ),
    ]
