# Generated by Django 3.2.3 on 2021-05-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('git_name', models.CharField(max_length=255, verbose_name='Git Name')),
            ],
            options={
                'verbose_name': 'Git Server',
                'verbose_name_plural': 'Git Servers',
            },
        ),
    ]
